// src/scaffolds/frontends/vue-antd/src/layouts/UserLayout.vue
<template>
    <a-layout class="u-layout">
        <a-layout-header class="u-header">
            <div class="u-header-inner">
                <div class="u-logo" @click="router.push('/user/home')">
                    <span class="u-logo-mark">S</span>
                    <span class="u-logo-text">脚手架平台</span>
                </div>

                <a-menu
                    mode="horizontal"
                    :selected-keys="[route.path]"
                    class="u-nav"
                    @click="({ key }) => router.push(key)"
                >
                    <a-menu-item key="/user/home">
                        <template #icon><home-outlined /></template>
                        首页
                    </a-menu-item>
                    <a-menu-item key="/user/notice">
                        <template #icon><bell-outlined /></template>
                        公告
                    </a-menu-item>
                </a-menu>

                <div class="u-actions">
                    <template v-if="userStore.token">
                        <a-dropdown placement="bottomRight">
                            <div class="u-user">
                                <a-avatar
                                    :src="userStore.userInfo?.avatar"
                                    :size="32"
                                >
                                    <template #icon><user-outlined /></template>
                                </a-avatar>
                                <span class="u-user-name">
                                    {{
                                        userStore.userInfo?.nickname ||
                                        userStore.userInfo?.username
                                    }}
                                </span>
                            </div>
                            <template #overlay>
                                <a-menu>
                                    <a-menu-item
                                        @click="router.push('/user/profile')"
                                    >
                                        <user-outlined /> 个人中心
                                    </a-menu-item>
                                    <a-menu-item
                                        v-if="
                                            userStore.userInfo?.role === 'admin'
                                        "
                                        @click="router.push('/admin/dashboard')"
                                    >
                                        <dashboard-outlined /> 管理后台
                                    </a-menu-item>
                                    <a-menu-divider />
                                    <a-menu-item @click="handleLogout">
                                        <logout-outlined /> 退出登录
                                    </a-menu-item>
                                </a-menu>
                            </template>
                        </a-dropdown>
                    </template>
                    <template v-else>
                        <a-button type="text" @click="router.push('/login')"
                            >登录</a-button
                        >
                        <a-button
                            type="primary"
                            @click="router.push('/register')"
                            >注册</a-button
                        >
                    </template>
                </div>
            </div>
        </a-layout-header>

        <a-layout-content class="u-content">
            <div class="u-content-inner">
                <router-view />
            </div>
        </a-layout-content>

        <a-layout-footer class="u-footer-slot">
            <app-footer />
        </a-layout-footer>
    </a-layout>
</template>

<script setup>
import { useRouter, useRoute } from "vue-router";
import { message } from "ant-design-vue";
import {
    HomeOutlined,
    BellOutlined,
    UserOutlined,
    LogoutOutlined,
    DashboardOutlined,
} from "@ant-design/icons-vue";
import { useUserStore } from "@/stores/user";
import AppFooter from "@/components/AppFooter.vue";
import "@/styles/user.css";

const router = useRouter();
const route = useRoute();
const userStore = useUserStore();

const handleLogout = () => {
    userStore.logout();
    message.success("退出成功");
    router.push("/login");
};
</script>

// src/scaffolds/frontends/react/src/layouts/UserLayout.jsx
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { Layout, Menu, Avatar, Dropdown, Button } from 'antd'
import {
  HomeOutlined,
  BellOutlined,
  UserOutlined,
  LogoutOutlined,
  DashboardOutlined
} from '@ant-design/icons'
import { useUserStore } from '../stores/userStore'
import AppFooter from '../components/AppFooter'
import '../styles/user.css'

const { Header, Content, Footer } = Layout

export default function UserLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const { token, userInfo, logout } = useUserStore()

  const menuItems = [
    { key: '/user/home', icon: <HomeOutlined />, label: '首页' },
    { key: '/user/notice', icon: <BellOutlined />, label: '公告' }
  ]

  const userMenu = [
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: '个人中心',
      onClick: () => navigate('/user/profile')
    },
    ...(userInfo?.role === 'admin'
      ? [
          {
            key: 'admin',
            icon: <DashboardOutlined />,
            label: '管理后台',
            onClick: () => navigate('/admin/dashboard')
          }
        ]
      : []),
    { type: 'divider' },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
      onClick: () => {
        logout()
        navigate('/login')
      }
    }
  ]

  return (
    <Layout className="u-layout">
      <Header className="u-header">
        <div className="u-header-inner">
          <div className="u-logo" onClick={() => navigate('/user/home')}>
            <span className="u-logo-mark">S</span>
            <span className="u-logo-text">脚手架平台</span>
          </div>

          <Menu
            mode="horizontal"
            selectedKeys={[location.pathname]}
            items={menuItems}
            onClick={({ key }) => navigate(key)}
            className="u-nav"
          />

          <div className="u-actions">
            {token ? (
              <Dropdown menu={{ items: userMenu }} placement="bottomRight">
                <div className="u-user">
                  <Avatar src={userInfo?.avatar} icon={<UserOutlined />} size={32} />
                  <span className="u-user-name">{userInfo?.nickname || userInfo?.username}</span>
                </div>
              </Dropdown>
            ) : (
              <>
                <Button type="text" onClick={() => navigate('/login')}>
                  登录
                </Button>
                <Button type="primary" onClick={() => navigate('/register')}>
                  注册
                </Button>
              </>
            )}
          </div>
        </div>
      </Header>

      <Content className="u-content">
        <div className="u-content-inner">
          <Outlet />
        </div>
      </Content>

      <Footer className="u-footer-slot">
        <AppFooter />
      </Footer>
    </Layout>
  )
}
