// src/scaffolds/frontends/vue-antd/src/views/Login.vue
<template>
    <div class="auth-screen">
        <div class="auth-card">
            <div class="auth-brand">
                <div class="auth-brand-mark">S</div>
                <div class="auth-brand-title">欢迎登录</div>
            </div>

            <a-form
                :model="form"
                ref="formRef"
                :rules="rules"
                size="large"
                @finish="handleSubmit"
            >
                <a-form-item name="username">
                    <a-input
                        v-model:value="form.username"
                        placeholder="用户名"
                        autocomplete="username"
                    >
                        <template #prefix><user-outlined /></template>
                    </a-input>
                </a-form-item>

                <a-form-item name="password">
                    <a-input-password
                        v-model:value="form.password"
                        placeholder="密码"
                        autocomplete="current-password"
                    >
                        <template #prefix><lock-outlined /></template>
                    </a-input-password>
                </a-form-item>

                <a-form-item name="captcha">
                    <div style="display: flex; gap: 8px">
                        <a-input
                            v-model:value="form.captcha"
                            placeholder="验证码"
                            autocomplete="off"
                            :maxlength="4"
                        >
                            <template #prefix><safety-outlined /></template>
                        </a-input>
                        <captcha ref="captchaRef" />
                    </div>
                </a-form-item>

                <a-form-item>
                    <a-button
                        type="primary"
                        html-type="submit"
                        block
                        :loading="loading"
                        >登录</a-button
                    >
                </a-form-item>

                <div class="auth-footer">
                    还没有账号？<router-link to="/register"
                        >立即注册</router-link
                    >
                </div>
            </a-form>
        </div>
    </div>
</template>

<script setup>
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { message } from "ant-design-vue";
import {
    UserOutlined,
    LockOutlined,
    SafetyOutlined,
} from "@ant-design/icons-vue";
import { useUserStore } from "@/stores/user";
import Captcha from "@/components/Captcha.vue";

const router = useRouter();
const userStore = useUserStore();
const loading = ref(false);
const formRef = ref(null);
const captchaRef = ref(null);
const form = reactive({ username: "", password: "", captcha: "" });
const rules = {
    username: [
        { required: true, message: "请输入用户名", trigger: "blur" },
        { min: 3, max: 50, message: "长度 3-50 个字符", trigger: "blur" },
    ],
    password: [
        { required: true, message: "请输入密码", trigger: "blur" },
        { min: 6, message: "密码至少 6 位", trigger: "blur" },
    ],
    captcha: [{ required: true, message: "请输入验证码", trigger: "blur" }],
};

const handleSubmit = async () => {
    if (!captchaRef.value.verify(form.captcha)) {
        message.error("验证码错误");
        captchaRef.value.refresh();
        form.captcha = "";
        return;
    }
    loading.value = true;
    try {
        const res = await userStore.login(form.username, form.password);
        message.success("登录成功");
        router.push(
            res.data.userInfo.role === "admin"
                ? "/admin/dashboard"
                : "/user/home",
        );
    } catch {
        captchaRef.value.refresh();
        form.captcha = "";
    } finally {
        loading.value = false;
    }
};
</script>

// src/scaffolds/frontends/react/src/views/Login.jsx
import { useRef, useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Form, Input, Button, message } from 'antd'
import { UserOutlined, LockOutlined, SafetyOutlined } from '@ant-design/icons'
import { useUserStore } from '../stores/userStore'
import Captcha from '../components/Captcha'

export default function Login() {
  const navigate = useNavigate()
  const login = useUserStore((state) => state.login)
  const [loading, setLoading] = useState(false)
  const captchaRef = useRef(null)

  const handleSubmit = async (values) => {
    // 前端验证码校验, 不走后端
    if (!captchaRef.current.verify(values.captcha)) {
      message.error('验证码错误')
      captchaRef.current.refresh()
      return
    }
    setLoading(true)
    try {
      const res = await login(values.username, values.password)
      message.success('登录成功')
      navigate(res.data.userInfo.role === 'admin' ? '/admin/dashboard' : '/user/home')
    } catch {
      captchaRef.current.refresh()
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="auth-screen">
      <div className="auth-card">
        <div className="auth-brand">
          <div className="auth-brand-mark">S</div>
          <div className="auth-brand-title">欢迎登录</div>
        </div>

        <Form onFinish={handleSubmit} size="large">
          <Form.Item
            name="username"
            rules={[
              { required: true, message: '请输入用户名' },
              { min: 3, max: 50, message: '长度 3-50 个字符' }
            ]}
          >
            <Input prefix={<UserOutlined />} placeholder="用户名" autoComplete="username" />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[
              { required: true, message: '请输入密码' },
              { min: 6, message: '密码至少 6 位' }
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="密码"
              autoComplete="current-password"
            />
          </Form.Item>

          <Form.Item name="captcha" rules={[{ required: true, message: '请输入验证码' }]}>
            <div style={{ display: 'flex', gap: 8 }}>
              <Input
                prefix={<SafetyOutlined />}
                placeholder="验证码"
                autoComplete="off"
                maxLength={4}
              />
              <Captcha ref={captchaRef} />
            </div>
          </Form.Item>

          <Form.Item>
            <Button type="primary" htmlType="submit" block loading={loading}>
              登录
            </Button>
          </Form.Item>

          <div className="auth-footer">
            还没有账号？<Link to="/register">立即注册</Link>
          </div>
        </Form>
      </div>
    </div>
  )
}
