// src/scaffolds/frontends/react/src/views/user/NoticeDetail.jsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Card, Descriptions, Button, Spin } from 'antd'
import { ArrowLeftOutlined } from '@ant-design/icons'
import { getNoticeById } from '../../api/notice'

export default function NoticeDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [detail, setDetail] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    getNoticeById(id)
      .then((res) => setDetail(res.data))
      .finally(() => setLoading(false))
  }, [id])

  if (loading) return <Spin spinning style={{ display: 'block', marginTop: 120 }} />

  if (!detail)
    return (
      <div className="detail-page">
        <p>公告不存在</p>
      </div>
    )

  return (
    <div>
      <Button
        icon={<ArrowLeftOutlined />}
        onClick={() => navigate(-1)}
        style={{ marginBottom: 16 }}
      >
        返回
      </Button>

      <h1 className="detail-title">{detail.title}</h1>
      <p className="detail-subtitle">
        发布于 <span className="text-muted">{detail.createTime}</span>
        {detail.updateTime !== detail.createTime && (
          <>
            {' '}
            · 更新于 <span className="text-muted">{detail.updateTime}</span>
          </>
        )}
      </p>

      <Card className="detail-section">
        <h2 className="section-title">基本信息</h2>
        <Descriptions bordered column={1} size="middle">
          <Descriptions.Item label="编号">
            <span className="text-primary">{detail.id}</span>
          </Descriptions.Item>
          <Descriptions.Item label="发布人">{detail.createBy || '-'}</Descriptions.Item>
          <Descriptions.Item label="发布时间">{detail.createTime}</Descriptions.Item>
          <Descriptions.Item label="更新时间">{detail.updateTime}</Descriptions.Item>
        </Descriptions>
      </Card>

      <Card className="detail-section">
        <h2 className="section-title">详细内容</h2>
        <div className="rich-content" dangerouslySetInnerHTML={{ __html: detail.content || '' }} />
      </Card>
    </div>
  )
}

// src/scaffolds/frontends/vue-naive/src/views/user/NoticeDetail.vue
<template>
  <div>
    <n-button @click="$router.back()">← 返回</n-button>

    <div v-if="loading" class="loading-wrapper">
      <n-spin size="medium" />
    </div>

    <div v-else-if="!detail" class="empty-notice">
      <p>公告不存在</p>
    </div>

    <template v-else>
      <h1 class="detail-title">{{ detail.title }}</h1>
      <p class="detail-subtitle">
        发布于 <span class="text-muted">{{ detail.createTime }}</span>
        <template v-if="detail.updateTime !== detail.createTime">
          · 更新于
          <span class="text-muted">{{ detail.updateTime }}</span>
        </template>
      </p>

      <n-card class="detail-section" title="基本信息">
        <n-descriptions bordered :column="1" size="medium">
          <n-descriptions-item label="编号">
            <span class="text-primary">{{ detail.id }}</span>
          </n-descriptions-item>
          <n-descriptions-item label="发布时间">
            {{ detail.createTime }}
          </n-descriptions-item>
          <n-descriptions-item label="更新时间">
            {{ detail.updateTime }}
          </n-descriptions-item>
        </n-descriptions>
      </n-card>

      <n-card class="detail-section" title="详细内容">
        <div class="rich-content" v-html="detail.content || ''" />
      </n-card>
    </template>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { NButton, NCard, NDescriptions, NDescriptionsItem, NSpin } from 'naive-ui'
import { getNoticeById } from '@/api/notice'

const route = useRoute()
const detail = ref(null)
const loading = ref(true)

onMounted(async () => {
  try {
    const res = await getNoticeById(route.params.id)
    detail.value = res.data
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
.loading-wrapper {
  display: flex;
  justify-content: center;
  padding: 80px 0;
}

.empty-notice {
  text-align: center;
  padding: 80px 0;
  color: #999;
  font-size: 15px;
}
</style>
