// src/scaffolds/frontends/react/src/layouts/AdminLayout.jsx
import { useState } from 'react'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { Layout, Menu, Avatar, Dropdown } from 'antd'
import {
  DashboardOutlined,
  UserOutlined,
  BellOutlined,
  FileTextOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined
} from '@ant-design/icons'
import { useUserStore } from '../stores/userStore'
import AppFooter from '../components/AppFooter'
import '../styles/admin.css'

const { Header, Sider, Content, Footer } = Layout

export default function AdminLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const { userInfo, logout } = useUserStore()
  const [collapsed, setCollapsed] = useState(false)

  const menuItems = [
    { key: '/admin/dashboard', icon: <DashboardOutlined />, label: '仪表盘' },
    { key: '/admin/user', icon: <UserOutlined />, label: '用户管理' },
    { key: '/admin/notice', icon: <BellOutlined />, label: '公告管理' },
    { key: '/admin/log', icon: <FileTextOutlined />, label: '日志管理' },
    { key: '/admin/status', icon: <DashboardOutlined />, label: '系统状态' }
  ]

  const userMenu = [
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: '个人中心',
      onClick: () => navigate('/admin/profile')
    },
    {
      key: 'userside',
      icon: <DashboardOutlined />,
      label: '用户端',
      onClick: () => navigate('/user/home')
    },
    { type: 'divider' },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
      onClick: () => {
        logout()
        navigate('/login')
      }
    }
  ]

  return (
    <Layout className="a-layout">
      <Sider trigger={null} collapsible collapsed={collapsed} width={220} className="a-sider">
        <div className="a-logo">
          <span className="a-logo-mark">S</span>
          {!collapsed && <span>后台管理</span>}
        </div>
        <Menu
          mode="inline"
          selectedKeys={[location.pathname]}
          items={menuItems}
          onClick={({ key }) => navigate(key)}
          className="a-menu"
        />
      </Sider>

      <Layout className="a-body">
        <Header className="a-header">
          <div className="a-header-left">
            {collapsed ? (
              <MenuUnfoldOutlined className="a-trigger" onClick={() => setCollapsed(false)} />
            ) : (
              <MenuFoldOutlined className="a-trigger" onClick={() => setCollapsed(true)} />
            )}
            <span className="a-breadcrumb">管理控制台</span>
          </div>
          <Dropdown menu={{ items: userMenu }} placement="bottomRight">
            <div className="a-user">
              <Avatar src={userInfo?.avatar} icon={<UserOutlined />} size={32} />
              <span className="a-user-name">
                {userInfo?.nickname || userInfo?.username || '未登录'}
              </span>
            </div>
          </Dropdown>
        </Header>

        <Content className="a-content">
          <Outlet />
        </Content>

        <Footer className="a-footer-slot">
          <AppFooter />
        </Footer>
      </Layout>
    </Layout>
  )
}

// src/scaffolds/frontends/vue-antd/src/layouts/AdminLayout.vue
<template>
    <a-layout class="a-layout">
        <a-layout-sider
            v-model:collapsed="collapsed"
            :trigger="null"
            collapsible
            :width="220"
            class="a-sider"
        >
            <div class="a-logo">
                <span class="a-logo-mark">S</span>
                <span v-if="!collapsed">后台管理</span>
            </div>
            <a-menu
                mode="inline"
                :selected-keys="[route.path]"
                class="a-menu"
                @click="({ key }) => router.push(key)"
            >
                <a-menu-item key="/admin/dashboard">
                    <template #icon><dashboard-outlined /></template>
                    仪表盘
                </a-menu-item>
                <a-menu-item key="/admin/user">
                    <template #icon><user-outlined /></template>
                    用户管理
                </a-menu-item>
                <a-menu-item key="/admin/notice">
                    <template #icon><bell-outlined /></template>
                    公告管理
                </a-menu-item>
                <a-menu-item key="/admin/log">
                    <template #icon><file-text-outlined /></template>
                    日志管理
                </a-menu-item>
                <a-menu-item key="/admin/status">
                    <template #icon><dashboard-outlined /></template>
                    系统状态
                </a-menu-item>
            </a-menu>
        </a-layout-sider>

        <a-layout class="a-body">
            <a-layout-header class="a-header">
                <div class="a-header-left">
                    <menu-unfold-outlined
                        v-if="collapsed"
                        class="a-trigger"
                        @click="collapsed = false"
                    />
                    <menu-fold-outlined
                        v-else
                        class="a-trigger"
                        @click="collapsed = true"
                    />
                    <span class="a-breadcrumb">管理控制台</span>
                </div>
                <a-dropdown placement="bottomRight">
                    <div class="a-user">
                        <a-avatar :src="userStore.userInfo?.avatar" :size="32">
                            <template #icon><user-outlined /></template>
                        </a-avatar>
                        <span class="a-user-name">
                            {{
                                userStore.userInfo?.nickname ||
                                userStore.userInfo?.username ||
                                "未登录"
                            }}
                        </span>
                    </div>
                    <template #overlay>
                        <a-menu>
                            <a-menu-item @click="router.push('/admin/profile')">
                                <user-outlined /> 个人中心
                            </a-menu-item>
                            <a-menu-item @click="router.push('/user/home')">
                                <dashboard-outlined /> 用户端
                            </a-menu-item>
                            <a-menu-divider />
                            <a-menu-item @click="handleLogout">
                                <logout-outlined /> 退出登录
                            </a-menu-item>
                        </a-menu>
                    </template>
                </a-dropdown>
            </a-layout-header>

            <a-layout-content class="a-content">
                <router-view />
            </a-layout-content>

            <a-layout-footer class="a-footer-slot">
                <app-footer />
            </a-layout-footer>
        </a-layout>
    </a-layout>
</template>

<script setup>
import { ref } from "vue";
import { useRouter, useRoute } from "vue-router";
import { message } from "ant-design-vue";
import {
    DashboardOutlined,
    UserOutlined,
    BellOutlined,
    FileTextOutlined,
    LogoutOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
} from "@ant-design/icons-vue";
import { useUserStore } from "@/stores/user";
import AppFooter from "@/components/AppFooter.vue";
import "@/styles/admin.css";

const router = useRouter();
const route = useRoute();
const userStore = useUserStore();
const collapsed = ref(false);

const handleLogout = () => {
    userStore.logout();
    message.success("退出成功");
    router.push("/login");
};
</script>
