// src/scaffolds/frontends/vue-elementplus/src/views/admin/UserManage.vue
<template>
  <el-card>
    <template #header>
      <div class="card-header">
        <span>用户管理</span>
        <div style="display: flex; gap: 8px">
          <el-button type="primary" @click="handleAdd">
            <el-icon><Plus /></el-icon> 添加用户
          </el-button>
          <el-button type="danger" :disabled="!selectedIds.length" @click="handleBatchDelete">
            <el-icon><Delete /></el-icon> 批量删除
          </el-button>
        </div>
      </div>
    </template>

    <div class="toolbar">
      <el-input
        v-model="filters.username"
        placeholder="搜索用户名"
        style="width: 220px"
        clearable
        @keydown.enter="onFilter"
      />
      <el-select
        v-model="filters.role"
        placeholder="选择角色"
        style="width: 150px"
        clearable
        @change="onFilter"
      >
        <el-option label="管理员" value="admin" />
        <el-option label="普通用户" value="user" />
      </el-select>
      <el-button type="primary" @click="onFilter">搜索</el-button>
    </div>

    <el-table
      v-loading="loading"
      :data="list"
      row-key="id"
      @selection-change="selectedIds = $event.map((r) => r.id)"
    >
      <el-table-column type="selection" width="50" />
      <el-table-column label="序号" width="70">
        <template #default="{ $index }">
          {{ (pageNum - 1) * pageSize + $index + 1 }}
        </template>
      </el-table-column>
      <el-table-column prop="username" label="用户名" width="120" />
      <el-table-column prop="nickname" label="昵称" width="120">
        <template #default="{ row }">{{ row.nickname || '-' }}</template>
      </el-table-column>
      <el-table-column prop="gender" label="性别" width="70">
        <template #default="{ row }">{{ genderLabel(row.gender) }}</template>
      </el-table-column>
      <el-table-column prop="age" label="年龄" width="70">
        <template #default="{ row }">{{ row.age || '-' }}</template>
      </el-table-column>
      <el-table-column prop="phone" label="手机号" width="130">
        <template #default="{ row }">{{ row.phone || '-' }}</template>
      </el-table-column>
      <el-table-column prop="email" label="邮箱" show-overflow-tooltip>
        <template #default="{ row }">{{ row.email || '-' }}</template>
      </el-table-column>
      <el-table-column prop="role" label="角色" width="110">
        <template #default="{ row }">
          <el-tag :type="row.role === 'admin' ? 'danger' : 'primary'">
            {{ row.role === 'admin' ? '管理员' : '普通用户' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="createTime" label="创建时间" width="170" />
      <el-table-column label="操作" width="180" fixed="right">
        <template #default="{ row }">
          <div class="table-actions">
            <el-button size="small" class="btn-edit" @click="handleEdit(row)">
              <el-icon><Edit /></el-icon> 编辑
            </el-button>
            <el-button size="small" class="btn-delete" @click="handleDelete(row.id)">
              <el-icon><Delete /></el-icon> 删除
            </el-button>
          </div>
        </template>
      </el-table-column>
    </el-table>

    <div class="pagination-wrap">
      <el-pagination
        v-model:current-page="pageNum"
        :page-size="pageSize"
        :total="total"
        layout="total, prev, pager, next"
        background
        @current-change="fetchList"
      />
    </div>

    <el-dialog v-model="modalVisible" :title="editing ? '编辑用户' : '添加用户'" width="640px">
      <el-alert
        type="info"
        :closable="false"
        show-icon
        style="margin-bottom: 16px"
        title="新增用户走注册接口，角色固定为普通用户；密码由用户自行在个人中心修改，此处不提供改密与改角色"
      />

      <div style="text-align: center; margin-bottom: 16px">
        <avatar-upload :value="avatar" @update:value="avatar = $event" :size="88" />
      </div>

      <el-form :model="form" :rules="rules" ref="formRef" label-position="top">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 0 16px">
          <el-form-item label="用户名" prop="username">
            <el-input v-model="form.username" placeholder="请输入用户名" :disabled="!!editing" />
          </el-form-item>
          <el-form-item v-if="!editing" label="密码" prop="password">
            <el-input
              v-model="form.password"
              type="password"
              placeholder="请输入密码"
              show-password
            />
          </el-form-item>
          <el-form-item label="昵称" prop="nickname">
            <el-input v-model="form.nickname" placeholder="请输入昵称" maxlength="50" />
          </el-form-item>
          <el-form-item label="年龄" prop="age">
            <el-input-number
              v-model="form.age"
              :min="1"
              :max="150"
              controls-position="right"
              style="width: 100%"
            />
          </el-form-item>
          <el-form-item label="性别" prop="gender">
            <el-select v-model="form.gender" placeholder="请选择性别" clearable style="width: 100%">
              <el-option
                v-for="o in GENDER_OPTIONS"
                :key="o.value"
                :label="o.label"
                :value="o.value"
              />
            </el-select>
          </el-form-item>
          <el-form-item label="手机号" prop="phone">
            <el-input v-model="form.phone" placeholder="请输入手机号" maxlength="11" />
          </el-form-item>
          <el-form-item label="邮箱" prop="email">
            <el-input v-model="form.email" placeholder="请输入邮箱" />
          </el-form-item>
        </div>
      </el-form>

      <template #footer>
        <el-button @click="modalVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSubmit">
          {{ editing ? '保存' : '添加' }}
        </el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup>
import { reactive, ref, onMounted, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Edit, Delete } from '@element-plus/icons-vue'
import { pageQueryUser, register, updateUser, deleteUser, deleteUserBatch } from '@/api/user'
import AvatarUpload from '@/components/AvatarUpload.vue'

const GENDER_OPTIONS = [
  { value: 'male', label: '男' },
  { value: 'female', label: '女' },
  { value: 'other', label: '其他' }
]
const genderLabel = (g) => GENDER_OPTIONS.find((o) => o.value === g)?.label || '-'

const loading = ref(false)
const list = ref([])
const total = ref(0)
const pageNum = ref(1)
const pageSize = 10
const selectedIds = ref([])
const filters = reactive({ username: '', role: '' })

const modalVisible = ref(false)
const editing = ref(null)
const avatar = ref('')
const formRef = ref(null)
const form = reactive({
  username: '',
  password: '',
  nickname: '',
  age: null,
  gender: '',
  phone: '',
  email: ''
})

const rules = computed(() => ({
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: editing.value ? [] : [{ required: true, message: '请输入密码', trigger: 'blur' }],
  phone: [{ pattern: /^1\d{10}$/, message: '手机号格式不正确', trigger: 'blur' }],
  email: [{ type: 'email', message: '邮箱格式不正确', trigger: 'blur' }]
}))

const fetchList = async () => {
  loading.value = true
  try {
    const res = await pageQueryUser({
      pageNum: pageNum.value,
      pageSize,
      username: filters.username,
      role: filters.role
    })
    list.value = res.data.records
    total.value = res.data.total
  } finally {
    loading.value = false
  }
}

const onFilter = () => {
  pageNum.value = 1
  fetchList()
}

const resetForm = (u = {}) => {
  form.username = u.username || ''
  form.password = ''
  form.nickname = u.nickname || ''
  form.age = u.age ?? null
  form.gender = u.gender || ''
  form.phone = u.phone || ''
  form.email = u.email || ''
  avatar.value = u.avatar || ''
}

const handleAdd = () => {
  editing.value = null
  resetForm()
  modalVisible.value = true
}
const handleEdit = (r) => {
  editing.value = r
  resetForm(r)
  modalVisible.value = true
}

const handleDelete = (id) => {
  ElMessageBox.confirm('确定要删除这个用户吗？', '确认删除', {
    type: 'warning',
    confirmButtonText: '删除',
    confirmButtonClass: 'el-button--danger'
  })
    .then(async () => {
      await deleteUser(id)
      ElMessage.success('删除成功')
      fetchList()
    })
    .catch(() => {})
}

const handleBatchDelete = () => {
  if (!selectedIds.value.length) return ElMessage.warning('请先选择要删除的用户')
  ElMessageBox.confirm(`确定要删除选中的 ${selectedIds.value.length} 个用户吗？`, '确认批量删除', {
    type: 'warning',
    confirmButtonText: '删除',
    confirmButtonClass: 'el-button--danger'
  })
    .then(async () => {
      await deleteUserBatch(selectedIds.value)
      ElMessage.success('批量删除成功')
      selectedIds.value = []
      fetchList()
    })
    .catch(() => {})
}

const handleSubmit = async () => {
  await formRef.value.validate()
  if (editing.value) {
    // 后端 update 接口只接收基本资料，username/role/password 不在此修改
    await updateUser({
      id: editing.value.id,
      nickname: form.nickname,
      age: form.age,
      gender: form.gender,
      phone: form.phone,
      email: form.email,
      avatar: avatar.value
    })
    ElMessage.success('更新成功')
  } else {
    // 注册接口角色由后端写死为 user
    await register({ ...form, avatar: avatar.value })
    ElMessage.success('添加成功')
  }
  modalVisible.value = false
  fetchList()
}

onMounted(fetchList)
</script>

<style scoped>
.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
</style>

// src/scaffolds/frontends/react/src/views/admin/UserManage.jsx
import { useState, useEffect, useCallback } from 'react'
import {
  Card,
  Table,
  Button,
  Input,
  InputNumber,
  Select,
  Space,
  Modal,
  Form,
  Tag,
  Alert,
  message
} from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons'
import { pageQueryUser, register, updateUser, deleteUser, deleteUserBatch } from '../../api/user'
import AvatarUpload from '../../components/AvatarUpload'
import ResizableTitle from '../../components/ResizableTitle'

const { Search } = Input

const GENDER_OPTIONS = [
  { value: 'male', label: '男' },
  { value: 'female', label: '女' },
  { value: 'other', label: '其他' }
]
const genderLabel = (g) => GENDER_OPTIONS.find((o) => o.value === g)?.label || '-'

export default function UserManage() {
  const [loading, setLoading] = useState(false)
  const [list, setList] = useState([])
  const [total, setTotal] = useState(0)
  const [pageNum, setPageNum] = useState(1)
  const pageSize = 10
  const [username, setUsername] = useState('')
  const [role, setRole] = useState('')
  const [selectedIds, setSelectedIds] = useState([])
  const [modalVisible, setModalVisible] = useState(false)
  const [editing, setEditing] = useState(null)
  const [avatar, setAvatar] = useState('')
  const [form] = Form.useForm()

  const fetchList = useCallback(async () => {
    setLoading(true)
    try {
      const res = await pageQueryUser({ pageNum, pageSize, username, role })
      setList(res.data.records)
      setTotal(res.data.total)
    } finally {
      setLoading(false)
    }
  }, [pageNum, username, role])

  useEffect(() => {
    fetchList()
  }, [fetchList])

  const handleAdd = () => {
    setEditing(null)
    setAvatar('')
    form.resetFields()
    setModalVisible(true)
  }

  const handleEdit = (record) => {
    setEditing(record)
    setAvatar(record.avatar || '')
    form.setFieldsValue(record)
    setModalVisible(true)
  }

  // 后端 update 接口不接收 role 与 password（防提权与越权改密），
  // 因此编辑时不展示这两个字段，避免“提示成功但实际未生效”
  const isEdit = !!editing

  const handleDelete = (id) => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除这个用户吗？',
      okButtonProps: { danger: true },
      onOk: async () => {
        await deleteUser(id)
        message.success('删除成功')
        fetchList()
      }
    })
  }

  const handleBatchDelete = () => {
    if (!selectedIds.length) return message.warning('请先选择要删除的用户')
    Modal.confirm({
      title: '确认批量删除',
      content: `确定要删除选中的 ${selectedIds.length} 个用户吗？`,
      okButtonProps: { danger: true },
      onOk: async () => {
        await deleteUserBatch(selectedIds)
        message.success('批量删除成功')
        setSelectedIds([])
        fetchList()
      }
    })
  }

  const handleSubmit = async () => {
    const values = await form.validateFields()
    const payload = { ...values, avatar }
    if (editing) {
      await updateUser({ ...payload, id: editing.id })
      message.success('更新成功')
    } else {
      await register(payload)
      message.success('添加成功')
    }
    setModalVisible(false)
    fetchList()
  }

  const columnsDef = [
    {
      title: '序号',
      key: 'idx',
      width: 70,
      render: (_, __, i) => (pageNum - 1) * pageSize + i + 1
    },
    { title: '用户名', dataIndex: 'username', width: 120 },
    {
      title: '昵称',
      dataIndex: 'nickname',
      width: 120,
      render: (v) => v || '-'
    },
    { title: '性别', dataIndex: 'gender', width: 70, render: genderLabel },
    { title: '年龄', dataIndex: 'age', width: 70, render: (v) => v || '-' },
    {
      title: '手机号',
      dataIndex: 'phone',
      width: 130,
      render: (v) => v || '-'
    },
    {
      title: '邮箱',
      dataIndex: 'email',
      ellipsis: true,
      render: (v) => v || '-'
    },
    {
      title: '角色',
      dataIndex: 'role',
      width: 110,
      render: (r) => (
        <Tag color={r === 'admin' ? 'red' : 'blue'}>{r === 'admin' ? '管理员' : '普通用户'}</Tag>
      )
    },
    { title: '创建时间', dataIndex: 'createTime', width: 170 },
    {
      title: '操作',
      key: 'op',
      width: 180,
      fixed: 'right',
      render: (_, r) => (
        <div className="table-actions">
          <Button
            size="small"
            className="btn-edit"
            icon={<EditOutlined />}
            onClick={() => handleEdit(r)}
          >
            编辑
          </Button>
          <Button
            size="small"
            className="btn-delete"
            icon={<DeleteOutlined />}
            onClick={() => handleDelete(r.id)}
          >
            删除
          </Button>
        </div>
      )
    }
  ]

  const [columns, setColumns] = useState(columnsDef)

  const handleResize = useCallback(
    (index) =>
      (_, { size }) => {
        setColumns((prev) => {
          const next = [...prev]
          next[index] = { ...next[index], width: Math.max(60, size.width) }
          return next
        })
      },
    []
  )

  const mergedColumns = columns.map((col, index) => ({
    ...col,
    onHeaderCell: (column) => ({
      width: column.width,
      onResize: handleResize(index)
    })
  }))

  const tableComponents = {
    header: { cell: ResizableTitle }
  }

  return (
    <Card
      title="用户管理"
      extra={
        <Space>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            添加用户
          </Button>
          <Button
            danger
            icon={<DeleteOutlined />}
            disabled={!selectedIds.length}
            onClick={handleBatchDelete}
          >
            批量删除
          </Button>
        </Space>
      }
    >
      <div className="toolbar">
        <Search
          placeholder="搜索用户名"
          onSearch={(v) => {
            setUsername(v)
            setPageNum(1)
          }}
          style={{ width: 220 }}
          allowClear
        />
        <Select
          placeholder="选择角色"
          onChange={(v) => {
            setRole(v || '')
            setPageNum(1)
          }}
          style={{ width: 150 }}
          allowClear
        >
          <Select.Option value="admin">管理员</Select.Option>
          <Select.Option value="user">普通用户</Select.Option>
        </Select>
      </div>

      <Table
        loading={loading}
        columns={mergedColumns}
        dataSource={list}
        rowKey="id"
        scroll={{ x: 'max-content' }}
        components={tableComponents}
        rowSelection={{
          selectedRowKeys: selectedIds,
          onChange: setSelectedIds
        }}
        pagination={{
          current: pageNum,
          pageSize,
          total,
          onChange: setPageNum,
          showTotal: (t) => `共 ${t} 条`
        }}
      />

      <Modal
        title={editing ? '编辑用户' : '添加用户'}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={() => setModalVisible(false)}
        width={640}
        okText={editing ? '保存' : '添加'}
        cancelText="取消"
      >
        <div style={{ textAlign: 'center', marginBottom: 16 }}>
          <AvatarUpload value={avatar} onChange={setAvatar} size={88} />
        </div>

        <Alert
          type="info"
          showIcon
          style={{ marginBottom: 16 }}
          message={
            isEdit
              ? '角色与密码不在本表单修改，后端已限制该接口只能更新基本资料'
              : '新建账号的角色固定为普通用户，由后端统一控制'
          }
        />

        <Form form={form} layout="vertical">
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: '1fr 1fr',
              gap: '0 16px'
            }}
          >
            <Form.Item
              label="用户名"
              name="username"
              rules={[{ required: true, message: '请输入用户名' }]}
            >
              <Input placeholder="请输入用户名" disabled={isEdit} />
            </Form.Item>
            {!isEdit && (
              <Form.Item
                label="密码"
                name="password"
                rules={[{ required: true, message: '请输入密码' }]}
              >
                <Input.Password placeholder="请输入密码" />
              </Form.Item>
            )}
            <Form.Item label="昵称" name="nickname">
              <Input placeholder="请输入昵称" maxLength={50} />
            </Form.Item>
            <Form.Item label="年龄" name="age">
              <InputNumber min={1} max={150} placeholder="年龄" style={{ width: '100%' }} />
            </Form.Item>
            <Form.Item label="性别" name="gender">
              <Select placeholder="请选择性别" allowClear options={GENDER_OPTIONS} />
            </Form.Item>
            <Form.Item
              label="手机号"
              name="phone"
              rules={[{ pattern: /^1\d{10}$/, message: '手机号格式不正确' }]}
            >
              <Input placeholder="请输入手机号" maxLength={11} />
            </Form.Item>
            <Form.Item
              label="邮箱"
              name="email"
              rules={[{ type: 'email', message: '邮箱格式不正确' }]}
            >
              <Input placeholder="请输入邮箱" />
            </Form.Item>
          </div>
        </Form>
      </Modal>
    </Card>
  )
}
